version: "3.7"

services:
  www:
    build:
      dockerfile: ./docker/web/Dockerfile
      context: .
    image: 109149/game-of-life
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./www/:/game-of-life/www
      - node_modules:/game-of-life/www/node_modules
    container_name: 109149-game-of-life-www

volumes:
  node_modules:
